### ISSUE TITLE
TypeScript error with import

### ISSUE THREAD

**Issue by sergous** [evgenyrodionov/redux-logger#208]
Using line from readme:

```
import createLogger from 'redux-logger';
let logger = createLogger();
```
Gives error:

```
TypeError: redux_logger_1.default is not a function
    at Object.<anonymous> (http://localhost:3000/index.js:52698:39)
    at __webpack_require__ (http://localhost:3000/index.js:20:30)
    at http://localhost:3000/index.js:66:18
    at http://localhost:3000/index.js:69:10
```

import * as createLogger from 'redux-logger'; 
fixes the issue;

Problem in Chrome  Version 59.0.3044.0 (Official Build) canary (64-bit), Windows

**Comment by evgenyrodionov** [comment]
Do you use TypeScript?

**Comment by manict** [comment]
gives error on Typescript 2.2.1
TypeError: Object is not a function (evaluating 'createLogger')

**Comment by evgenyrodionov** [comment]
IDK, never used TypeScript

**Comment by mcrawshaw** [comment]
Pull request created:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15293

This should fix the issue.

**Comment by mcrawshaw** [comment]
Fixed with DT PR:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15295

**Comment by mcrawshaw** [comment]
Fixed with PR:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15296

**Comment by mcrawshaw** [comment]
Npm @types will be updated shortly with a new definition file.  This only works with 2.10.1 (not 2.10.2).
Waiting on the discussion to clear up at https://github.com/evgenyrodionov/redux-logger/issues/210 before I (possibly) update for > 10.10.1.
